pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
  - name: automatic PR merge for krugazul (ready-to-merge)
    conditions:
      - author=krugazul
      - label=ready-to-merge
    actions:
      merge:
        method: merge
